name = "skyrellac-devs"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_APP_URL = "https://skyrellac-devs.preetham171977.workers.dev"
RAZORPAY_KEY_ID = "rzp_live_TWpB2OW5IF4Jcn"
RAZORPAY_KEY_SECRET = "oQsNrwwQjS6nXIzN4mdhzN3o"
NEXT_PUBLIC_RAZORPAY_KEY_ID = "rzp_live_TWpB2OW5IF4Jcn"
MONGODB_URI = "mongodb+srv://skyrellac:skyrellac123@cluster0.mongodb.net/skyrellac?retryWrites=true&wmode=majority"
