import { Course, LearningPath, Internship, Credential, Test } from '../types/database';

export const MOCK_COURSES: Course[] = [
  {
    id: 'f1000000-0000-0000-0000-000000000001',
    title: 'Artificial Intelligence Fundamentals',
    slug: 'ai-fundamentals',
    description: 'Master foundational artificial intelligence concepts, neural networks, machine learning algorithms, and responsible AI ethics.',
    category_name: 'Artificial Intelligence',
    difficulty: 'Foundational',
    duration_minutes: 240,
    lesson_count: 12,
    credential_available: true,
    is_published: true,
    skills: ['Python', 'Machine Learning', 'Responsible AI', 'Neural Networks'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'f1000000-0000-0000-0000-000000000002',
    title: 'Full-Stack Modern Web Engineering',
    slug: 'full-stack-web-engineering',
    description: 'Build enterprise web applications with Next.js 14, modern TypeScript, Tailwind CSS, clean API routes and scalable database integration.',
    category_name: 'Software Development',
    difficulty: 'Intermediate',
    duration_minutes: 360,
    lesson_count: 16,
    credential_available: true,
    is_published: true,
    skills: ['React & Next.js', 'TypeScript', 'Tailwind CSS', 'PostgreSQL'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'f1000000-0000-0000-0000-000000000003',
    title: 'Applied Data Science & SQL Analytics',
    slug: 'data-science-sql-analytics',
    description: 'Learn high-performance database querying, data cleaning, statistically sound data modeling, and automated visualization pipelines.',
    category_name: 'Data & Analytics',
    difficulty: 'Foundational',
    duration_minutes: 300,
    lesson_count: 14,
    credential_available: true,
    is_published: true,
    skills: ['SQL', 'Python', 'Data Visualization', 'Pandas'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'f1000000-0000-0000-0000-000000000004',
    title: 'Cloud Infrastructure & DevOps Mastery',
    slug: 'cloud-infrastructure-devops',
    description: 'Deploy containerized cloud workloads, implement CI/CD automated deployment pipelines, and configure secure server architecture.',
    category_name: 'Cloud Computing',
    difficulty: 'Advanced',
    duration_minutes: 420,
    lesson_count: 18,
    credential_available: true,
    is_published: true,
    skills: ['Docker', 'AWS', 'Kubernetes', 'CI/CD Pipelines'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'f1000000-0000-0000-0000-000000000005',
    title: 'Cybersecurity Principles & Threat Audit',
    slug: 'cybersecurity-principles-audit',
    description: 'Understand network security defenses, vulnerability testing, risk management, and security protocols for modern corporate environments.',
    category_name: 'Cybersecurity',
    difficulty: 'Intermediate',
    duration_minutes: 280,
    lesson_count: 10,
    credential_available: true,
    is_published: true,
    skills: ['Network Security', 'Vulnerability Assessment', 'Cryptography', 'Audit'],
    created_at: new Date().toISOString(),
  },
];

export const MOCK_LEARNING_PATHS: LearningPath[] = [
  {
    id: 'p1000000-0000-0000-0000-000000000001',
    title: 'AI & Machine Learning Engineer Path',
    slug: 'ai-machine-learning-engineer',
    description: 'A structured 7-stage learning journey taking you from Python programming fundamentals to production Deep Learning models.',
    icon: 'Brain',
    estimated_hours: 45,
    is_published: true,
    courses: [MOCK_COURSES[0], MOCK_COURSES[2]],
  },
  {
    id: 'p1000000-0000-0000-0000-000000000002',
    title: 'Full-Stack Web Architect Path',
    slug: 'full-stack-web-architect',
    description: 'Master frontend user experience, scalable backend APIs, database management, and cloud deployment pipelines.',
    icon: 'Layers',
    estimated_hours: 50,
    is_published: true,
    courses: [MOCK_COURSES[1], MOCK_COURSES[3]],
  },
  {
    id: 'p1000000-0000-0000-0000-000000000003',
    title: 'Cybersecurity Specialist Path',
    slug: 'cybersecurity-specialist',
    description: 'Prepare for cybersecurity certifications and hands-on threat defense analysis in corporate networks.',
    icon: 'Shield',
    estimated_hours: 35,
    is_published: true,
    courses: [MOCK_COURSES[4]],
  },
];

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: 'i1000000-0000-0000-0000-000000000001',
    title: 'AI & Machine Learning Engineering Intern',
    slug: 'ai-ml-engineering-intern',
    organization_name: 'Skyrellac Innovation Labs',
    mode: 'Remote',
    location: 'Global / Remote',
    duration_weeks: 8,
    description: 'Work alongside senior AI research scientists to preprocess domain datasets, evaluate Transformer language models, and assist in model finetuning.',
    responsibilities: '• Build Python data cleaning and feature engineering pipelines.\n• Evaluate model loss and accuracy benchmarks.\n• Participate in weekly technical architecture reviews.',
    eligibility: 'Open to undergraduate students, graduates, and self-taught developers with strong Python and linear algebra basics.',
    required_skills: ['Python', 'Machine Learning', 'PyTorch', 'SQL'],
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'i1000000-0000-0000-0000-000000000002',
    title: 'Full-Stack Developer Intern',
    slug: 'full-stack-developer-intern',
    organization_name: 'Global Tech Solutions',
    mode: 'Remote',
    location: 'Global / Remote',
    duration_weeks: 12,
    description: 'Develop frontend UI components and RESTful microservices for high-traffic enterprise applications using React, Next.js, and modern TypeScript.',
    responsibilities: '• Create reusable glassmorphic UI components.\n• Integrate backend API routes with PostgreSQL databases.\n• Write clean, testable TypeScript code.',
    eligibility: 'Basic knowledge of JavaScript/TypeScript, HTML/CSS, and Git version control.',
    required_skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'i1000000-0000-0000-0000-000000000003',
    title: 'Data Analyst & BI Intern',
    slug: 'data-analyst-bi-intern',
    organization_name: 'Enterprise Data Systems',
    mode: 'Hybrid',
    location: 'Tech City HQ / Remote',
    duration_weeks: 10,
    description: 'Transform raw business data into actionable executive insights, automated interactive dashboards, and optimized SQL database reports.',
    responsibilities: '• Execute complex SQL joins and aggregations.\n• Design interactive data reporting dashboards.\n• Present findings to product teams.',
    eligibility: 'Familiarity with SQL, Excel/Google Sheets, and data visualization principles.',
    required_skills: ['SQL', 'Python', 'Data Analytics', 'Tableau'],
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'i1000000-0000-0000-0000-000000000004',
    title: 'Cloud Infrastructure & DevOps Intern',
    slug: 'cloud-devops-intern',
    organization_name: 'Apex Cloud Technologies',
    mode: 'Remote',
    location: 'Global / Remote',
    duration_weeks: 8,
    description: 'Gain hands-on experience managing Kubernetes cluster configurations, Terraform infrastructure code, and automated CI/CD build scripts.',
    responsibilities: '• Monitor cloud infrastructure health metrics.\n• Assist in building GitHub Actions deployment scripts.\n• Document infrastructure setups.',
    eligibility: 'Enthusiasm for Linux terminal commands, Docker containerization, and networking basics.',
    required_skills: ['Docker', 'AWS', 'Linux', 'CI/CD'],
    is_published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'i1000000-0000-0000-0000-000000000005',
    title: 'Cybersecurity Threat Analyst Intern',
    slug: 'cybersecurity-analyst-intern',
    organization_name: 'SecureShield Systems',
    mode: 'Remote',
    location: 'Global / Remote',
    duration_weeks: 12,
    description: 'Monitor network security logs, assist in vulnerability assessments, and conduct penetration testing in sandbox environments.',
    responsibilities: '• Analyze security event telemetry for anomalies.\n• Assist in vulnerability patch audits.\n• Author technical incident reports.',
    eligibility: 'Completed foundational cybersecurity coursework or certifications.',
    required_skills: ['Cybersecurity', 'Network Auditing', 'Linux', 'Python'],
    is_published: true,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_CREDENTIALS: Credential[] = [
  {
    id: 'cred-001',
    credential_id: 'SKY-AI-2026-00123',
    user_id: 'usr-1',
    user_name: 'Alex Johnson',
    course_id: 'f1000000-0000-0000-0000-000000000001',
    title: 'Artificial Intelligence Fundamentals',
    issue_date: '2026-08-18',
    skills_list: ['AI Fundamentals', 'Machine Learning', 'Responsible AI'],
  },
  {
    id: 'cred-002',
    credential_id: 'SKY-WEB-2026-00456',
    user_id: 'usr-1',
    user_name: 'Alex Johnson',
    course_id: 'f1000000-0000-0000-0000-000000000002',
    title: 'Full-Stack Modern Web Engineering',
    issue_date: '2026-08-10',
    skills_list: ['React', 'Next.js', 'TypeScript', 'PostgreSQL'],
  },
];
